### PR TITLE
Include header file to declare out_hook_nl

### PR DESCRIPTION
**Pull request by drj11**
I don't know, these modern C99 compilers complaining that you can't use code before declaring it.

I know macOS isn't a supported platform, but when i try and `bmake -r` in `/trans` i am _stopped_ by some so-called C99 validation:

```
; bmake -r
==> Compiling src/common/main/print.c
cc -D TRANS_X86 -I /Users/drj/prj/tendra/trans/src/x86 -I /Users/drj/prj/tendra/trans/src/common -D TDF_DIAG4 -D DWARF2 -D STABS -I ..  -I /Users/drj/prj/tendra/trans/include  -c print.c -o /Users/drj/prj/tendra/trans/obj/src/x86/_partial/src/common/main/print.o
print.c:49:5: error: implicit declaration of function 'out_hook_nl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                out_hook_nl();
                                ^
1 error generated.
*** Error code 1
```

I assume there is no cosmic reason why `print.c` should not include `out.h`, so i added the include. That fixes this compilation error.

### CODE REVIEW

**Comment by drj11** [comment]
Oh, maybe there is a cosmic reason that involves architecture specific include paths that i don't understand.

**Comment by hvdijk** [comment]
Probably the only change you will need to get this to pass is wrap the `#include` in `#if defined(TRANS_X86)`...`#endif`.

**Comment by drj11** [comment]
Oh the `out_hook_nl()` function is only called from within ` #if defined(TRANS_X86)`. right.

I mean, this is all legal in c89, although considered a bad practice by many; it only became actually wrong in C1999

**Comment by drj11** [comment]
I remove the `#include`.

I guess on some level you could say that i should add `-std=c89` to the compiler on macOS and this would go away. But it's nice to imagine that one day c99 compilers could be used.

**Comment by hvdijk** [comment]
This is valid, but I am slightly confused: why do you not want to include the header that contains the declaration?

**Comment by drj11** [comment]
i don't like an explosion of `#if`s and i wasn't prepared to check or vouch that the textual contents of `out.h` were valid  to `#include` from within the function definition. Whereas i knew it was valid to declare the single function that is used.

Ever seen the C source to the Plan 9 shell `rc`? It uses this style throughout. Or used to.

**Comment by katef** [comment]
I'd definitely prefer we include the header here; copy-pasting the prototype in-situ is just asking for drift.

Here's an example of a similar case, for common/ code including local/ stuff:
```
trans/src/common/flpt/flpt_fns.c:#ifdef TRANS_POWER
trans/src/common/flpt/flpt_fns.c-#include <local/cpu.h>
trans/src/common/flpt/flpt_fns.c:#endif
```
(try not to read the read of that file :D)

**Comment by drj11** [comment]
i mean, i'd prefer that DWARF didn't require what looks like a Monstrous Hack on x86, but here we are.

I'll change it to the #if guarded include.

**Comment by drj11** [comment]
I've done like i was taught in school now.

**Review by katef — APPROVED** [review]
Thanks!
